//
//
//███████╗██╗██████╗ ███████╗███████╗ ██████╗ ██╗  ██╗
//██╔════╝██║██╔══██╗██╔════╝██╔════╝██╔═══██╗╚██╗██╔╝
//█████╗  ██║██████╔╝█████╗  █████╗  ██║   ██║ ╚███╔╝ 
//██╔══╝  ██║██╔══██╗██╔══╝  ██╔══╝  ██║   ██║ ██╔██╗ 
//██║     ██║██║  ██║███████╗██║     ╚██████╔╝██╔╝ ██╗
//╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚═╝      ╚═════╝ ╚═╝  ╚═╝
//                                                    
// Mozilla User Preferences
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

//user_pref("accessibility.typeaheadfind", true);
//user_pref("accessibility.typeaheadfind.flashBar", 0);
//user_pref("app.normandy.first_run", false);
user_pref("browser.bookmarks.openInTabClosesMenu", false);
//user_pref("browser.bookmarks.restore_default_bookmarks", false);
//user_pref("browser.cache.disk.capacity", 153600);
//user_pref("browser.cache.disk.filesystem_reported", 1);
//user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.cache.offline.insecure.enable", false);
//user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", true);
user_pref("browser.display.background_color", "#666666");
//user_pref("browser.download.autohideButton", false);
//user_pref("browser.download.panel.shown", true);
user_pref("browser.fullscreen.autohide", false);
//user_pref("browser.laterrun.bookkeeping.sessionCount", 25);
//user_pref("browser.laterrun.enabled", true);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.prerender", false);
//user_pref("browser.newtabpage.pinned", "[]");
//user_pref("browser.newtabpage.storageVersion", 1);
//user_pref("browser.onboarding.notification.prompt-count", 4);
//user_pref("browser.onboarding.notification.tour-ids-queue", "");
//user_pref("browser.onboarding.seen-tourset-version", 2);
//user_pref("browser.onboarding.state", "watermark");
//user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.onboarding.tour.onboarding-tour-addons.completed", true);
user_pref("browser.onboarding.tour.onboarding-tour-customize.completed", true);
user_pref("browser.onboarding.tour.onboarding-tour-default-browser.completed", true);
user_pref("browser.onboarding.tour.onboarding-tour-performance.completed", true);
user_pref("browser.onboarding.tour.onboarding-tour-private-browsing.completed", true);
user_pref("browser.onboarding.tour.onboarding-tour-screenshots.completed", true);
user_pref("browser.onboarding.tour.onboarding-tour-sync.completed", true);
//user_pref("browser.pagethumbnails.storage_version", 3);
//user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.preferences.defaultPerformanceSettings.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("browser.search.context.loadInBackground", true);
user_pref("browser.search.countryCode", "FR");
user_pref("browser.search.region", "FR");
user_pref("browser.search.suggest.enabled", false);
//user_pref("browser.search.useDBForOrder", true);
user_pref("browser.send_pings", false);
user_pref("browser.sessionstore.privacy_level", 2);
//user_pref("browser.sessionstore.restore_on_demand", false);
user_pref("browser.shell.checkDefaultBrowser", true);
//user_pref("browser.slowStartup.averageTime", 0);
//user_pref("browser.slowStartup.samples", 0);
//user_pref("browser.tabs.drawInTitlebar", true);
//user_pref("browser.tabs.extraDragSpace", true);
user_pref("browser.tabs.loadBookmarksInBackground", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
//user_pref("browser.uidensity", 1);
user_pref("browser.urlbar.autoFill", false);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("browser.urlbar.doubleClickSelectsAll", false);
user_pref("browser.urlbar.formatting.enabled", false);
//user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
//user_pref("browser.urlbar.searchSuggestionsChoice", false);
user_pref("browser.urlbar.speculativeConnect.enabled", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.searches", false);
//user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("browser.urlbar.trimURLs", false);
//user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("devtools.editor.keymap", "vim");
//user_pref("devtools.inspector.activeSidebar", "computedview");
//user_pref("devtools.inspector.three-pane-first-run", false);
//user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.theme", "dark");
//user_pref("devtools.toolbox.footer.height", 380);
//user_pref("devtools.toolbox.selectedTool", "inspector");
//user_pref("devtools.toolbox.tabsOrder", "inspector,webconsole,jsdebugger,styleeditor,performance,memory,netmonitor,storage,https-everywhere@eff.org");
//user_pref("devtools.toolsidebar-height.inspector", 350);
//user_pref("devtools.toolsidebar-width.inspector", 700);
//user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("devtools.webextensions.https-everywhere@eff.org.enabled", true);
//user_pref("distribution.archlinux.bookmarksProcessed", true);
//user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.battery.enabled", false);
user_pref("dom.event.clipboardevents.enabled", false);
user_pref("dom.ipc.processCount", 7);
//user_pref("extensions.blocklist.pingCountTotal", 6);
//user_pref("extensions.blocklist.pingCountVersion", 6);
//user_pref("extensions.databaseSchema", 27);
user_pref("extensions.formautofill.addresses.enabled", false);
user_pref("extensions.formautofill.creditCards.enabled", false);
user_pref("extensions.formautofill.firstTimeUse", false);
user_pref("extensions.formautofill.heuristics.enabled", false);
user_pref("extensions.formautofill.section.enabled", false);
user_pref("extensions.formautofill.supportRTL", true);
//user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.enabled", false);
//user_pref("extensions.ui.dictionary.hidden", true);
//user_pref("extensions.ui.lastCategory", "addons://list/extension");
//user_pref("extensions.ui.locale.hidden", false);
user_pref("findbar.highlightAll", true);
user_pref("findbar.modalHighlight", true);
user_pref("font.internaluseonly.changed", false);
user_pref("font.name.monospace.x-western", "Iosevka");
user_pref("font.name.sans-serif.x-western", "Overpass Nerd Font mono");
user_pref("font.name.serif.x-western", "Overpass Nerd Font Mono");
user_pref("full-screen-api.warning.timeout", 0);
user_pref("general.autoScroll", true);
user_pref("general.smoothScroll", false);
user_pref("general.warnOnAboutConfig", false);
user_pref("geo.enabled", false);
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("layers.acceleration.force-enabled", true);
user_pref("layout.css.prefixes.webkit", false);
//user_pref("layout.spellcheckDefault", 0);
//user_pref("lightweightThemes.persisted.footerURL", false);
//user_pref("lightweightThemes.persisted.headerURL", false);
user_pref("lightweightThemes.selectedThemeID", "firefox-compact-dark@mozilla.org");
//user_pref("lightweightThemes.usedThemes", "[]");
//user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.navigator.enabled", false);
//user_pref("media.peerconnection.ice.proxy_only", true);
user_pref("middlemouse.paste", false);
user_pref("network.IDN_show_punycode", true);
user_pref("network.cookie.cookieBehavior", 4);
//user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.referer.XOriginPolicy", 2);
user_pref("network.http.referer.XOriginTrimmingPolicy", 2);
user_pref("network.http.referer.trimmingPolicy", 2);
//user_pref("network.http.speculative-parallel-limit", 0);
//user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
//user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
//user_pref("pref.downloads.disable_button.edit_actions", false);
//user_pref("pref.general.disable_button.default_browser", false);
//user_pref("pref.privacy.disable_button.cookie_exceptions", false);
//user_pref("privacy.clearOnShutdown.cookies", false);
//user_pref("privacy.clearOnShutdown.passwords", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.donottrackheader.value", 1);
user_pref("privacy.firstparty.isolate", true);
user_pref("privacy.firstparty.isolate.restrict_opener_access", true);
//user_pref("privacy.history.custom", true);
user_pref("privacy.resistFingerprinting", true);
//user_pref("privacy.sanitize.pending", "[{\"id\":\"shutdown\",\"itemsToClear\":[\"cache\",\"history\",\"formdata\",\"downloads\",\"sessions\"],\"options\":{}},{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("privacy.spoof_english", 2);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.introCount", 20);
user_pref("privacy.userContext.enabled", true);
//user_pref("privacy.userContext.longPressBehavior", 2);
user_pref("privacy.userContext.ui.enabled", true);
user_pref("security.ssl.treat_unsafe_negotiation_as_broken", true);
//user_pref("services.settings.clock_skew_seconds", -30);
user_pref("services.sync.prefs.sync.browser.search.selectedEngine", true);
user_pref("services.sync.prefs.sync.browser.tabs.closeButtons", true);
user_pref("services.sync.prefs.sync.browser.urlbar.default.behavior", true);
user_pref("services.sync.prefs.sync.lightweightThemes.isThemeSelected", true);
user_pref("services.sync.prefs.sync.privacy.clearOnShutdown.passwords", true);
user_pref("services.sync.prefs.sync.privacy.donottrackheader.value", true);
user_pref("signon.autofillForms", false);
user_pref("signon.autofillForms.Http", false);
user_pref("signon.importedFromSqlite", true);
user_pref("signon.rememberSignons", false);
//user_pref("spellchecker.dictionary", "en-US");
//user_pref("storage.vacuum.last.index", 1);
user_pref("toolkit.cosmeticAnimations.enabled", false);
//user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.key.menuAccessKeyFocuses", false);
user_pref("webgl.disabled", true);
