#! /bin/sh

~/.config/polybar/launch.sh &

sxhkd &

setxkbmap us -variant intl &
unclutter --timeout 3 --ignore scrolling &
~/scripts/touchpad_toggle.sh &

xset -dpms &
xset s off &
xset -b &

urxvtd -q -o -f &
compton --config ~/.config/compton.conf &
dunst &
redshift-gtk &
nm-applet &
udiskie --use-udisks2 &
nextcloud &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
